sudo: false
language: elixir

otp_release:
  - 18.2
  - 17.5

elixir:
  - 1.3.0
  - 1.2.0
  - 1.1.1

matrix:
  exclude:
    - elixir: 1.2.0
      otp_release: 17.5
    - elixir: 1.3.0
      otp_release: 17.5

env:
  - MIX_ENV=test

script:
  - mix test --trace
